package com.suning.facade.manager.entity;

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.suning.common.entity.BaseEntity;
@Table(name = "suning_content")
public class Content extends BaseEntity{
    /**
	 * 
	 */
	private static final long serialVersionUID = -771407405340098250L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.category_id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.sub_title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.title_desc
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String titleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.url
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.pic
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.pic2
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String pic2;

 
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suning_content.content
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.id
     *
     * @return the value of suning_content.id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.id
     *
     * @param id the value for suning_content.id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.category_id
     *
     * @return the value of suning_content.category_id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.category_id
     *
     * @param categoryId the value for suning_content.category_id
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.title
     *
     * @return the value of suning_content.title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.title
     *
     * @param title the value for suning_content.title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.sub_title
     *
     * @return the value of suning_content.sub_title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.sub_title
     *
     * @param subTitle the value for suning_content.sub_title
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.title_desc
     *
     * @return the value of suning_content.title_desc
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getTitleDesc() {
        return titleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.title_desc
     *
     * @param titleDesc the value for suning_content.title_desc
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc == null ? null : titleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.url
     *
     * @return the value of suning_content.url
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.url
     *
     * @param url the value for suning_content.url
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.pic
     *
     * @return the value of suning_content.pic
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.pic
     *
     * @param pic the value for suning_content.pic
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.pic2
     *
     * @return the value of suning_content.pic2
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.pic2
     *
     * @param pic2 the value for suning_content.pic2
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suning_content.content
     *
     * @return the value of suning_content.content
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suning_content.content
     *
     * @param content the value for suning_content.content
     *
     * @mbg.generated Sat Nov 18 10:51:43 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}